#!/usr/bin/perl -w

require "../MatrixReal.pm";

$matrix1 = Math::MatrixReal->new_from_string(<<"MATRIX");
[ 5 0 ]
[ 0 -6 ]
MATRIX

$ans1=$matrix1->clone();
$ans2=$matrix1->clone();
print "inverse is\n" . $ans1^(-1). "\n";
print "Overloaded: 1/matrix is\n" . 1/$matrix1 . "\n";


$ans1= 2 / $ans1;
$ans2= $ans2 / 2;

print "ans1:\n $ans1\n";
print "ans2:\n $ans2\n";

$ans1 = $ans1 / $ans1;
print "ans1:\n $ans1\n";
